### ISSUE TITLE
New data: Airplay Media - The Netherlands

### ISSUE THREAD

**Issue by HansVanEijsden** [Opendigitalradio/opendigitalradio.github.io#5]
Hi there! Here is my new submission. We have a test license, valid until January 2018 (but I'm quite sure it will be extended and continued).

			"type": "Feature",
				"properties": {
					"name": "De Nieuwe Hanze",
					"channel": "7B",
					"location": "Kampen, Overijssel, Netherlands",
					"start": "09.2017",
					"operator": "Airplay Media - Hans van Eijsden",
					"operatorUrl": "https://www.airplayradio.nl/",
                                        "moreInfoUrl": "https://www.facebook.com/airplayradio/"
				},
				"geometry": {
					"type": "Point",
					"coordinates": [5.911225, 52.550791]
				}

Coverage map:
![bereik berekening 7b kampen](https://user-images.githubusercontent.com/11890145/30295653-9b709c22-9741-11e7-8fcc-5895ab7cb96e.jpg)

**Comment by basicmaster** [comment]
Thanks!
