### ISSUE TITLE
DAB+ 4 Brainport

### ISSUE THREAD

**Issue by glokhoff** [Opendigitalradio/opendigitalradio.github.io#7]
Just to notify you that we've started regular DAB+ transmissions using OpenDigitalRadio software in the Eindhoven, Netherlands region:

    type of transmission: regular
    name of the multiplex: DAB+ 4 Brainport
    DAB channel of the multiplex: 7B
    name of the area covered: Eindhoven region
    the date the transmission began: 25.05.2020
    name of the operator: EUregio Digitaal Foundation for DABall76 project
    URL of the operator: https://www.euregiodigitaal.nl
    additional information URL: https://www.euregiodigitaal.nl/DABall76
    geographical coordinates: 5.481316, 51.435172

**Comment by mpbraendli** [comment]
Thanks for the notice. I've added the information with some changes, because your SSL certificate is invalid, and the second URL is invalid.
Let me know if that's fine.
